### PR TITLE
Added JSONP support

### PR DESCRIPTION
**Pull request by 0x62**

### CODE REVIEW

**Comment by robdudley** [comment]
Happy to merge this in but curious as to why it's needed. Is the server not running x domain correctly?

**Comment by robdudley** [comment]
BTW that's merged and pulled - feel free to test it out

**Comment by 0x62** [comment]
X Domain works fine, but for super light application where you only need the data once on load it makes life a bit easier - no need to for AJAX.

**Comment by robdudley** [comment]
Fair enough. Well that's in, let me know if it doesn't work :)

**Pull request merged**
